API 27264 - IT for Verification.
department-of-veterans-affairs/lighthouse-veteran-verification pull request #203
Opened 2023-06-12 20:35 UTC by Shoaib-VA

2023-06-12 20:47 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/VeteranStatusV2IT.java
> +    assumeEnvironmentNotIn(Environment.PROD, Environment.STAGING);
You dont need this here, since its defined in the @BeforeAll method.

2023-06-12 20:48 UTC, dlennon-va approved these changes

2023-06-12 20:48 UTC, dlennon-va requested changes
comments from previous review

2023-06-14 14:46 UTC, Shoaib-VA commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/VeteranStatusV2IT.java
> +    assumeEnvironmentNotIn(Environment.PROD, Environment.STAGING);
makes sense, thanks!

2023-06-15 13:45 UTC, dlennon-va approved these changes

2023-06-15 15:20 UTC, merged