create service history transformer
department-of-veterans-affairs/lighthouse-veteran-verification pull request #23
Opened 2021-07-02 20:53 UTC by lukemarkwordtlibertyits

2021-07-12 21:12 UTC, esubocz-va requested changes

2021-07-12 21:12 UTC, esubocz-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/utils/ServiceEpisodeAttributeBuilder.java
> +                dateTimeFormatter);
null checks.

to minimize repeating null checks, the date parsing can probably be pulled out into a method in the Transformers.java Utility Class.

2021-07-12 21:12 UTC, esubocz-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/utils/ServiceEpisodeIdBuilder.java
> +  public String buildServiceEpisodeId(String uuid, String beginDate, String endDate) {
I think this method would be better suited in the transformer, and for this class to maybe become a more uuid specific utility class of static methods, rather than a builder.

2021-07-14 20:37 UTC, beaugrantham-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/controller/veteranverification/VeteranServiceHistoryTransformer.java
> +    ArrayList<Deployment> list = new ArrayList<>();
This should be using an interface (`List`) along with the method return type.

Surprised that this is not caught by one of the code scanning plugins.

2021-07-14 20:55 UTC, beaugrantham-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/controller/veteranverification/VeteranServiceHistoryTransformer.java
> +    ArrayDeque<ServiceHistoryResponse.ServiceHistoryEpisode> episodes = new ArrayDeque<>();
Same here, should be an interface.

2021-07-14 21:10 UTC, beaugrantham-va commented on veteran-verification/src/test/java/gov/va/api/lighthouse/veteranverification/service/utils/ServiceEpisodeAttributeBuilderTest.java
> +  public void HappyPathDeploymentsEmpty() {
Use Java naming conventions. Again, the code scanning plugins should be picking this up. Are they configured correctly?

2021-07-14 23:41 UTC, lukemarkwordtlibertyits commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/utils/ServiceHistoryUtils.java
> +public class ServiceHistoryUtils {
I agree this utilities class isnt the right move. I wanted to keep my branch of service and pay grade unit test though to keep code coverage up. And the tests describe how the work. I didnt want to put it all in the transformer as well. I decided to place the pay grade and branch of service methods into their own objects. The logic to build them is in the toString method which will be what is rendered to json when called. I

2021-07-15 14:38 UTC, beaugrantham-va commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +          case "A":
This would be better done with the codes as part of the enum.

```
HONORABLE("A", "honorable")
```

The `codeToEnum` method then just finds the enum with the matching code.

As new codes are added, changes don't need to be made to both the enum and this method.

2021-07-15 14:39 UTC, beaugrantham-va commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +            // Or should this be unknown
Should it? What is the current VV behavior? This should match whatever that is.

2021-07-15 14:43 UTC, beaugrantham-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/MpiLookupUtils.java
> +    } catch (Exception e) {
This is bad practice to catch a generic exception. It will mask bugs and make diagnosing a problem very difficult.

2021-07-15 14:47 UTC, esubocz-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/MpiLookupUtils.java
> +    } catch (Exception e) {
+1 ^
Optional.Nullable I think would be a good option. MpiLookupUtils.java getInputEdipiOrIcn() method is a good example of that.

2021-07-16 15:40 UTC, dbrown-va commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +            // Or should this be unknown
Current VV is default unknown.

https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/veteran_verification/app/models/veteran_verification/service_history_episode.rb#L88

```
    def discharge_status
      EMISRedis::MilitaryInformationV2::EXTERNAL_DISCHARGE_TYPES[discharge_type] || 'unknown'
    end
```

Agreed that it should match vets-api it functionality.  I wouldn't be opposed to a log here in case this pops up in the future unexpectedly.

2021-07-16 22:25 UTC, lukemarkwordtlibertyits commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/MpiLookupUtils.java
> +    } catch (Exception e) {
Per Emily's suggestion I have used the Option nullable chain for these methods

2021-07-16 23:54 UTC, lukemarkwordtlibertyits commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +            // Or should this be unknown
I currently have it implemented so it will return an unknown, did not add a logger but can if desired.

2021-07-19 18:30 UTC, dbrown-va reviewed
One property that can be moved rather than in the pom dependency.

2021-07-19 18:30 UTC, dbrown-va commented on veteran-verification/pom.xml
> +      <version>3.0.1</version>
One more candidate version to move up into the properties section.

2021-07-19 20:39 UTC, dbrown-va commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +      UNKNOWN(null, "unknown");
vets-api based discharge types has a `'Z' => 'unknown'` option that I think we want to maintain even if it defaults to unknown when a match isn't found.

2021-07-19 22:24 UTC, dbrown-va submitted a review, later dismissed
As you mentioned in the thread, the unit test resources xml grows pretty large here, but I think it accurately tests the deserializing and then transforming of the model objects.

Only alternative I could think of is we fill specific parameters of an emis response xml as part of the unit test helper method.

```
<NS8:branchOfServiceCode>{{unit-test-value-branch}}</NS8:branchOfServiceCode>
<NS8:payPlanCode>{{unit-test-value-ppc}}</NS8:payPlanCode>
<NS8:payGradeCode>{{unit-test-value-pgc}}</NS8:payGradeCode>
```

Since they are tied to specific unit tests, they can be read in a pretty straightforward manner.

2021-07-19 23:15 UTC, lukemarkwordtlibertyits commented
> As you mentioned in the thread, the unit test resources xml grows pretty large here, but I think it accurately tests the deserializing and then transforming of the model objects.
> 
> Only alternative I could think of is we fill specific parameters of an emis response xml as part of the unit test helper method.
> 
> ```
> <NS8:branchOfServiceCode>{{unit-test-value-branch}}</NS8:branchOfServiceCode>
> <NS8:payPlanCode>{{unit-test-value-ppc}}</NS8:payPlanCode>
> <NS8:payGradeCode>{{unit-test-value-pgc}}</NS8:payGradeCode>
> ```
> 
> Since they are tied to specific unit tests, they can be read in a pretty straightforward manner.

@dbrown-va if Emily approves, I may merge and then try this technique in a new branch if that is ok with you?

2021-07-20 13:42 UTC, esubocz-va requested changes
A few small things, but for the most part looks good 👍

2021-07-20 13:42 UTC, esubocz-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/controller/veteranverification/VeteranServiceHistoryTransformer.java
> +  private LocalDate xmlGregorianToLocalDate(XMLGregorianCalendar calendar) {
This could probably go in the Transformers.java utility class.

2021-07-20 13:42 UTC, esubocz-va commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/v0/ServiceHistoryResponse.java
> +      @Override
Overriding the toString method seems a bit awkward to me, is there an added benefit to it vs a plain transforming method?

2021-07-20 13:42 UTC, esubocz-va commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/MpiLookupUtils.java
> +        .orElse(null);
The optional looks good 👍 it will still throw a null pointer exception in the transformer though, which is the goal to avoid.
for getEdipiOrIcn, the null check is performed in the veteran status transformer, and returns a veteran status `not confirmed`. 

is there an existing behavior for a null first/last name in vets-api that we could implement? If not I'd recommend adding a catch to the web exception handler to give a more detailed message rather than what will probably be a long awkward stack trace.

2021-07-20 18:26 UTC, esubocz-va approved these changes

2021-07-20 18:36 UTC, lukemarkwordtlibertyits commented on veteran-verification/src/main/java/gov/va/api/lighthouse/veteranverification/service/MpiLookupUtils.java
> +        .orElse(null);
For context: the current open-api specs are based on actual behavior and not desired behavior. lighthouse-veteran-verification gets user names from different sources than vets-api. While it is not possible to have a null user name filed in vets-api currently it is in lighthouse-veteran-verification. For this reason, Emily and I have decided to allow the user name fields to be nullable in this implementation of service history.

2021-07-20 18:49 UTC, merged