Api 18882 remove keys endpoint
department-of-veterans-affairs/lighthouse-veteran-verification pull request #89
Opened 2022-09-08 15:48 UTC by Shoaib-VA

Removes /keys endpoint per API-18882

2022-09-08 15:56 UTC, amizan8653-va submitted a review, later dismissed

2022-09-08 15:57 UTC, dbrown-va commented
The /keys endpoint was at one time utilized by USAJobs consumer.

It is also advertised in the OpenAPI spec and each resource as a valid response type.

Would caution removal without fulling removing the related capability.

2022-09-08 15:59 UTC, dbrown-va commented
> The /keys endpoint was at one time utilized by USAJobs consumer.
> 
> It is also advertised in the OpenAPI spec and each resource as a valid response type.
> 
> Would caution removal without fully removing the related capability.

The Media type `application/jwt` relies on the public key fetching capability with the /keys endpoint.
![image](https://user-images.githubusercontent.com/43859081/189169587-c8d3212f-c903-4f29-89e5-83c8d37dbece.png)

2022-09-08 16:07 UTC, dbrown-va commented
I think it would be great to simplify Veteran Verification to just the application/json response type.

Just want to ensure it doesn't unexpectedly have to be revived for a consumer and that we don't 1/2 remove it but still offer the application/jwt response type that can no longer be verified.

2022-09-08 16:20 UTC, dlennon-va requested changes
Based on Derek's feedback, lets make sure all mention of Keys is removed from the OpenApi specifications. And the content type of application/jwt is not supported on the existing endpoints (in code and the OAS).

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/main/docker/entrypoint.sh
> -  if [ -n "${OAUTH_VETERAN_CREDENTIALS_AUDIENCE:-}" ]; then addToSystemProperties "oauth.veteran-credentials.audience" "${OAUTH_VETERAN_CREDENTIALS_AUDIENCE}"; fi
I'm not so sure these should be gone, as OAuth will still be part of this app. We are just removing the JWK method of retrieving data.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/DisabilityRatingOauthIT.java
> -package gov.va.api.lighthouse.veteranverification.tests;
This is an OAuth test, doesn't look like its touching JWT things

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/Requestor.java
> -  static ExpectedResponse veteranVerificationTokenGetRequest(
This looks like its needed for OAuth tests.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/DisabilityRatingOauthIT.java
> -    assertNotNull(disabilityRatingJwt);
This is probably all we need to remove from this test.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/ServiceHistoryOauthIT.java
> -package gov.va.api.lighthouse.veteranverification.tests;
This is an OAuth test and not all JWT.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/ServiceHistoryOauthIT.java
> -    assertNotNull(serviceHistoryJwt);
This should be all we are removing

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/TestUtils.java
> -  public static final Set<String> SCOPES =
Probably still need all this.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/VeteranStatusOauthIT.java
> -package gov.va.api.lighthouse.veteranverification.tests;
This is an OAuth test and not all JWT, it should stay.

2022-09-14 14:16 UTC, dlennon-va commented on veteran-verification/src/test/java/gov/va/api/lighthouse/veteranverification/service/controller/keys/KeysControllerTest.java
This file should be deleted.

2022-09-14 14:29 UTC, aaronhietpas commented on veteran-verification-tests/pom.xml
> -    </dependency>
I think this will be required for the OAuth tests still

2022-09-14 14:31 UTC, aaronhietpas commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/VeteranVerificationServiceV1.java
> -      summary = "Retrieve disability rating of authorized Veteran",
Security info here will need to be added back on all of these endpoints

2022-09-14 14:32 UTC, aaronhietpas commented on veteran-verification-api/src/main/java/gov/va/api/lighthouse/veteranverification/api/VeteranVerificationServiceV1.java
> -      security = {@SecurityRequirement(name = "bearer_token")})
Security info here will need to be added back to all endpoints

2022-09-15 13:15 UTC, dlennon-va reviewed
Just a couple small test comments, otherwise we are looking good. Let's get those addressed and merge conflicts resolved, then will have Derek take one final look to double check.

2022-09-15 13:15 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/DisabilityRatingOauthIT.java
> -    assertNotNull(disabilityRatingJwt);
This is the only part of this test we should delete, the rest is testing the normal json version of the endpoint.

2022-09-15 13:15 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/ServiceHistoryOauthIT.java
> -    assertNotNull(serviceHistoryJwt);
Only should be removing this part of the test, the rest is testing the normal json endpoint.

2022-09-19 19:36 UTC, Shoaib-VA commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/ServiceHistoryOauthIT.java
> -    assertNotNull(serviceHistoryJwt);
done and verified

2022-09-19 20:43 UTC, dlennon-va commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/DisabilityRatingOauthIT.java
>      ExpectedResponse response =
You put the ServiceHistory back here, should be DisabilityRating test.

2022-09-19 21:02 UTC, dlennon-va commented
@dbrown-va Can you take one more look when you get a chance? Should have all the key/jwk fully removed now.

2022-09-19 22:59 UTC, dbrown-va commented on postman-collection/VA Veteran Confirmation & Verification.postman_collection.json
> +					"name": "Veteran Verification JWS Validation Keys",
Looks like there are still some endpoint references in this Postman collection.

2022-09-19 23:13 UTC, dbrown-va reviewed
Just the one comment on the Postman collection side with /keys straggler.

I see a few unresolved comments on the PR (that do _seem_ to be resolved), so will defer to @dlennon-va and team for final approval / merging.

2022-09-20 13:29 UTC, aaronhietpas commented on veteran-verification-tests/src/test/java/gov/va/api/lighthouse/veteranverification/tests/DisabilityRatingOauthIT.java
> +import static gov.va.api.lighthouse.veteranverification.tests.TestUtils.*;
Remove .* import and import all individually.

Can configure IntelliJ to not automatically add these.

2022-09-20 13:58 UTC, Shoaib-VA reviewed
verified all files, seems like all requested changes have been incorporated.

2022-09-20 14:39 UTC, dlennon-va approved these changes

2022-09-20 19:49 UTC, merged